version: "3"
services:
  bot:
    build: .
    environment:
      BOT_ID: $BOT_ID
      INSTANCE_ID: $INSTANCE_ID
    volumes:
      - ./:/go/src/tetona
    working_dir: /go/src/tetona
    command: "go run main.go"
