name: Go Status Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Whole Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run go vet
        run: go vet ./...

      - name: Run go build
        run: go build .

      - name: Run go test
        run: go test -v ./...
